title: PySTARS
description: Python STARS / ANASTAARS optimization algorithms
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

aux_links:
  GitHub Repo: https://github.com/KrishnaRauniyar/RanDFO
nav_external_links_new_tab: true

just_the_docs:
  aux_links: {}
  css: 
    - /assets/css/custom.scss


